package vn.com.gsoft.report.model.dto;

import lombok.Data;
import vn.com.gsoft.report.entity.PhieuXuatChiTiets;
import vn.com.gsoft.report.model.system.BaseRequest;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.UUID;

@Data
public class PhieuXuatsReq extends BaseRequest {
    private Long soPhieuXuat;
    private Date ngayXuat;
    private Integer vat;
    private String dienGiai;
    private BigDecimal tongTien;
    private BigDecimal daTra;
    private String nhaThuocMaNhaThuoc;
    private Integer maLoaiXuatNhap;
    private Long khachHangMaKhachHang;
    private Long nhaCungCapMaNhaCungCap;
    private Integer bacSyMaBacSy;
    private Boolean active;
    private Boolean isModified;
    private Boolean locked;
    private Boolean isDebt;
    private Date preNoteDate;
    private String connectivityNoteID;
    private Long connectivityStatusID;
    private String connectivityResult;
    private Date connectivityDateTime;
    private Long orderId;
    private BigDecimal discount;
    private BigDecimal score;
    private BigDecimal preScore;
    private Long archivedId;
    private Long storeId;
    private Long targetId;
    private Long sourceId;
    private Long sourceStoreId;
    private Long targetStoreId;
    private Long partnerId;
    private Long prescriptionId;
    private UUID uId;
    private String invoiceCode;
    private String invoiceNo;
    private String referenceKey;
    private Date invoiceDate;
    private BigDecimal paymentScore;
    private BigDecimal paymentScoreAmount;
    private Long bonusPaymentId;
    private String invoiceTemplateCode;
    private String invoiceSeries;
    private String invoiceType;
    private Date archivedDate;
    private BigDecimal prePaymentScore;
    private Long synStatusId;
    private BigDecimal transPaymentAmount;
    private Long paymentTypeId;
    private BigDecimal debtPaymentAmount;
    private BigDecimal backPaymentAmount;
    private String linkFile;
    private String doctorComments;
    private String keyNewEInvoice;
    private String keyOldEInvoice;
    private Long eInvoiceStatusID;
    private Long signEInvoiceStatusID;
    private Date connEInvoiceDateTime;
    private Date signEInvoiceDateTime;
    private Date destroyEInvoiceDateTime;
    private Date replacedEInvoiceDateTime;
    private Date editedEInvoiceDateTime;
    private String kHHDon;
    private String kHMSHDon;
    private String sHDon;
    private Long pickUpOrderId;
    private String eSampleNoteCode;
    private String linkConfirm;
    private String taxAuthorityCode;
    private String eInvoiveResult;
    private Boolean isRefSampleNote;
    private Date nextPurchaseDate;
    private String trackingIdZNS;
    private String resultZNS;
    private Long idPaymentQR;
    private Long targetManagementId;

    private Boolean IsConnectivity;

    private List<PhieuXuatChiTiets> chiTiets;
}
